# Generated by Django 3.0 on 2019-12-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('s_name', models.CharField(max_length=36)),
                ('uid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mobile_no', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
