# Generated by Django 3.0 on 2019-12-20 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_mobilenumber_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilenumber',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiledata', to='exam.Student'),
        ),
    ]
