# Generated by Django 3.0 on 2019-12-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('roll', models.CharField(max_length=10, unique=True)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
