# Generated by Django 3.0 on 2019-12-19 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('or', '0002_auto_20191219_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilenumber',
            options={'ordering': ['mobile']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['roll']},
        ),
        migrations.AlterField(
            model_name='mobilenumber',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='or.Student'),
        ),
    ]
