# Generated by Django 3.0 on 2019-12-19 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('or', '0004_auto_20191219_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilenumber',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='or.Student'),
        ),
    ]
