# Generated by Django 3.0 on 2019-12-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='posts.Category'),
        ),
    ]
