# Generated by Django 3.0 on 2019-12-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_posts_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='posts',
            table='posts',
        ),
    ]
